blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/open-dicom/csa_header#readme
    about: Check the README for usage information and examples
  - name: Discussions
    url: https://github.com/open-dicom/csa_header/discussions
    about: Ask questions and discuss ideas with the community
